dist: bionic
install:
- sudo apt-get update
- sudo apt-get install --reinstall ca-certificates

language: go
env:
- GO111MODULE=on

go:
- 1.15.x

script:
- go build -v -race ./...
- diff -u <(echo -n) <(gofmt -d .)
- go vet ./...
- go test -v -race ./...

branches:
  only: 
    - master
